[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
installers = ["homebrew", "shell"]
tap = "corca-ai/homebrew-tap"
formula = "awiki"
publish-jobs = ["homebrew"]
allow-dirty = ["ci"]
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
